// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPp0UH7-45spnJ8mUD1r-JZSLzy76fADw',
    appId: '1:468698923073:android:a54a4634df2a927abfc6c0',
    messagingSenderId: '927649659743',
    projectId: 'ecommerce-c2e80',
    // databaseURL: 'https://levelup-11900-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-c2e80.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBPp0UH7-45spnJ8mUD1r-JZSLzy76fADw',
  //   appId: '1:927649659743:ios:edcee72700288e3e6d54ea',
  //   messagingSenderId: '927649659743',
  //   projectId: 'ecommerce-c2e80',
  //   databaseURL: 'https://levelup-11900-default-rtdb.firebaseio.com',
  //   storageBucket: 'levelup-11900.appspot.com',
  //   iosClientId: '927649659743-if4akjuc0l8jfbis1235df0ublnsd2mq.apps.googleusercontent.com',
  //   iosBundleId: 'com.growthschool.app',
  // );
}
